### ISSUE TITLE
editing yaml for environment variables

### ISSUE THREAD

**Issue by emuhack** [tarfeef101/raptoreum_miner_docker#3]
I edited the yaml with these 

#environment:
   - THREADS=12
   - URL=stratum+tcp://us.flockpool.com:4444
   - USERNAME=(INSERTMINERADDRESS).3900xD
   - TUNE_FULL=FALSE

getting error or docker compose 
yaml: line 12: did not find expected key

How are you suppose to comment in the variables in your build?

**Comment by tarfeef101** [comment]
can you post the full YAML in a block
```
like so?
```
please? I suspect you're having an issue with your YAML syntax, especially if that `environment` line is still commented out like your post seems to indicate

edit: seems you've noticed your syntax error, I'll just edit this rather than spam your email with another post. if you've got another problem after resolving that, feel free to post, otherwise if everything's resolved, feel free to close :)

**Comment by emuhack** [comment]
```
version: "3"

services:
  mining:
    image: tarfeef101/raptorminer
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
  #environment:
      - THREADS=12
      - URL=stratum+tcp://us.flockpool.com:4444
      - USERNAME=(MINERADDRESS).3900xD
      - TUNE_FULL=FALSE

    #volumes:
     # - "./tune_config:/opt/tune_config"
```

That is how it is now

**Comment by emuhack** [comment]
error 
```
(root) Additional property environment is not allowed
````

here is the yaml
```
services:
  mining:
    image: tarfeef101/raptorminer
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
environment:
     THREADS=12
     URL=stratum+tcp://us.flockpool.com:4444
     USERNAME=(MINERADDRESS).3900xD
     TUNE_FULL=FALSE
```

**Comment by tarfeef101** [comment]
> - Snip -

I highly recommend reading over the [compose file specification](https://docs.docker.com/compose/compose-file/compose-file-v3/), will help prevent such errors in the future. In this case, `environment` is a property of a `service`, not a top-level value. So that's why you're still having issues. Seems like some review of YAMLs and/or the compose spec is in need here, though.

**Comment by emuhack** [comment]
I'm still learning all this and I really don't understand all that. lol
could I ask for some hand holding

**Comment by tarfeef101** [comment]
```
services:
  mining:
    image: tarfeef101/raptorminer
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
    environment:
      THREADS=12
      URL=stratum+tcp://us.flockpool.com:4444
      USERNAME=(MINERADDRESS).3900xD
      TUNE_FULL=FALSE
```

it should actually look something like this. I highly recommend looking up a guide about how YAMLs work (not a complicated specification). [this](https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started) might be good, no idea, but it's probably fine. and once you have that basic understanding, the previous link about compose will make more sense
