### ISSUE TITLE
tune_config not being written

### ISSUE THREAD

**Issue by emuhack** [tarfeef101/raptoreum_miner_docker#4]
I did the full tune 220min and after it did not correctly write the tune_config file in the directory that was uncommented in the yaml, no error just no file. It created a tune_config dir but no file created. I then tried to take a tune_config file from my vm (samecpu) and put it in in the tune_config dir, but when you start the container it says it cant find the file.

```
Could not find/load 'tune_config' file. Miner will perform tuning operation.
```

Thoughts?

**Comment by tarfeef101** [comment]
I think that's expected behaviour. the `tune_config` in the volumes section is NOT a directory, it is a file. so if you place a `tune_config` file in the same directory as your compose file, it will be mounted in

**Comment by emuhack** [comment]
this is dir of the directory

```
root@eMu-Unraid:/opt/raptoreum_miner_docker# dir
Dockerfile  README.md  build.sh  devops  docker-compose.yaml  entrypoint.sh  healthcheck.sh  tune_config
root@eMu-Unraid:/opt/raptoreum_miner_docker# 
```
i put the tune_config in the root with the compose, get the following error.

```
⠿ Container raptoreum_miner_docker-mining-1  Starting                                                                 0.2s
Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/opt/raptoreum_miner_docker/tune_config" to rootfs at "/var/lib/docker/btrfs/subvolumes/f145df50efa8ac45d8e2e944d95c2330bb818589c7c558d204472e694fe6e3ac/opt/tune_config" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Comment by tarfeef101** [comment]
sadly in that first snippet, I cannot tell if `tune_config` is a directory or not. I also cannot be sure that you have left the line I commented out in `main` intact or not (minus the commenting character, ofc). 

But the error is pretty clear, you probably have `tune_config` as a FOLDER on your host instead of a FILE. if you type `file tune_config` it should tell you what it is, and it will probably say it is a folder.

**Comment by emuhack** [comment]
```
root@eMu-Unraid:/opt/raptoreum_miner_docker# file tune_config
tune_config: ASCII text
root@eMu-Unraid:/opt/raptoreum_miner_docker# 
```

and if you mean (main) as in the yaml here it is how it stands

```
services:
  mining:
    image: tarfeef101/raptorminer
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
    environment:
     - THREADS=16
     - URL=stratum+tcp://us.flockpool.com:4444
     - USERNAME=xxxxxxxxxxxxx.3900xD
     - TUNE_FULL=false
    volumes:
      - "./tune_config:/opt/tune_config"
```
